<!DOCTYPE html>
<html>
<head>
    <title>Success Stories Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .story {
            margin-bottom: 30px;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .story-header {
            background-color: #f8f9fa;
            padding: 10px;
            margin: -20px -20px 15px -20px;
            border-radius: 5px 5px 0 0;
            border-bottom: 1px solid #ddd;
        }
        .story-title {
            font-size: 18px;
            font-weight: bold;
            color: #333;
            margin-bottom: 5px;
        }
        .story-meta {
            color: #666;
            font-size: 12px;
        }
        .story-content {
            margin-top: 15px;
            text-align: justify;
        }
        .participants {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
        }
        .participant {
            flex: 1;
            text-align: center;
        }
        .participant-label {
            font-weight: bold;
            color: #555;
        }
        .summary {
            background-color: #e9ecef;
            padding: 15px;
            margin-bottom: 30px;
            border-radius: 5px;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Nakitara Success Stories Report</h1>
        <p>Generated on {{ now()->format('F j, Y \a\t g:i A') }}</p>
        <p>Total Success Stories: {{ $stories->count() }}</p>
    </div>

    <div class="summary">
        <h3>Report Summary</h3>
        <p>This report contains {{ $stories->count() }} success stories from the Nakitara Lost & Found system. 
        These stories represent successful reunions between people and their lost items, facilitated through our platform.</p>
    </div>

    @foreach($stories as $index => $story)
        <div class="story">
            <div class="story-header">
                <div class="story-title">
                    {{ $story->item->title ?? 'Unknown Item' }}
                </div>
                <div class="story-meta">
                    Story #{{ $story->id }} | Created: {{ $story->created_at->format('M j, Y') }}
                </div>
            </div>

            <div class="participants">
                <div class="participant">
                    <div class="participant-label">Item Owner</div>
                    <div>{{ $story->owner->name ?? 'Unknown' }}</div>
                    <div style="font-size: 12px; color: #666;">{{ $story->owner->email ?? '' }}</div>
                </div>
                <div class="participant">
                    <div class="participant-label">Finder</div>
                    <div>{{ $story->finder->name ?? 'Unknown' }}</div>
                    <div style="font-size: 12px; color: #666;">{{ $story->finder->email ?? '' }}</div>
                </div>
            </div>

            <div class="story-content">
                <strong>Success Story:</strong><br>
                {{ $story->story }}
            </div>

            @if($story->item)
                <div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid #eee;">
                    <strong>Item Details:</strong><br>
                    <small>
                        Type: {{ ucfirst($story->item->type) }} | 
                        Category: {{ $story->item->category->name ?? 'No Category' }} |
                        Posted: {{ $story->item->created_at->format('M j, Y') }}
                    </small>
                </div>
            @endif
        </div>

        @if($index < $stories->count() - 1 && ($index + 1) % 2 == 0)
            <div class="page-break"></div>
        @endif
    @endforeach

    <div style="margin-top: 50px; text-align: center; color: #666; font-size: 12px;">
        <p>This report was generated by the Nakitara Lost & Found System</p>
        <p>For more information, visit our platform or contact support</p>
    </div>
</body>
</html>